#!/usr/bin/expect -f
set timeout 600
spawn ssh -o StrictHostKeyChecking=no root@5.180.149.170
expect {
    "*password:*" {
        send "47kvUyH~uu5dcwjM\r"
    }
}
expect "#" {
    send "cd /home/forge/instashpro && docker compose build backend\r"
}
expect "#" {
    send "cd /home/forge/instashpro && docker compose up -d backend\r"
}
expect "#" {
    send "docker exec instash-backend php artisan db:seed --class=UserSeeder --force\r"
}
expect "#" {
    send "exit\r"
}
expect eof
