#!/usr/bin/expect -f
set timeout 1800
spawn ssh -o StrictHostKeyChecking=no root@5.180.149.170
expect {
    "*password:*" {
        send "47kvUyH~uu5dcwjM\r"
    }
}
expect "#" {
    send "cd /home/forge/instashpro && git pull origin main\r"
}
expect "#" {
    send "cd /home/forge/instashpro && docker compose up -d\r"
}
expect "#" {
    send "docker restart deployment-nginx\r"
}
expect "#" {
    send "exit\r"
}
expect eof
