#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no root@5.180.149.170
expect {
    "*password:*" {
        send "47kvUyH~uu5dcwjM\r"
    }
}
expect "#" {
    send "rm /home/forge/deployment/nginx-configs/sites-enabled/instash.conf\r"
}
expect "#" {
    send "cp /home/forge/instashpro/instash.conf /home/forge/deployment/nginx-configs/sites-enabled/instash.conf\r"
}
expect "#" {
    send "docker restart deployment-nginx\r"
}
expect "#" {
    send "exit\r"
}
expect eof
